# build.sr.ht

image: alpine/latest

packages:
  - openjdk17-jre-headless

sources:
  - https://git.sr.ht:~jomco/eduhub-validator

tasks:
  - clojure: |
      curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
      sh linux-install-1.11.1.1273.sh -p `pwd`
  - babashka: |
      curl -L -O https://github.com/babashka/babashka/releases/download/v1.3.182/babashka-1.3.182-linux-amd64-static.tar.gz
      tar zxf babashka-1.3.182-linux-amd64-static.tar.gz
      mv bb `pwd`/bin
  - lint: |
      PATH=$PATH:`pwd`/bin
      cd eduhub-validator
      clojure -M:clj-kondo --lint src
  - test: |
      PATH=$PATH:`pwd`/bin
      cd eduhub-validator
      clojure -M:test
  - test-bb: |
      PATH=$PATH:`pwd`/bin
      cd eduhub-validator
      bb -Sdeps '{:deps {this/project {:local/root "."} lambdaisland/kaocha {:mvn/version "1.85.1342"}}}' -m kaocha.runner/-main
