# SPDX-FileCopyrightText: 2024, 2025, 2026 SURF B.V.
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0
# SPDX-FileContributor: Joost Diepenmaat
# SPDX-FileContributor: Remco van 't Veer

name: Check dependency vulnerabilities

on:
  workflow_call:

jobs:
  nvd:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/clojure
      with: { m2_cache_key: m2-nvd }

    - name: Check clojure dependencies with NVD
      run: |
        make nvd
