# SPDX-FileCopyrightText: 2026 SURF B.V.
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0

on:
  push: { branches: [ "main", "master" ] }

jobs:
  check:
    uses: ./.github/workflows/jobs/check.yml

  nvd:
    uses: ./.github/workflows/jobs/nvd.yml
