# SPDX-FileCopyrightText: 2024, 2025, 2026 SURF B.V.
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0
# SPDX-FileContributor: Joost Diepenmaat
# SPDX-FileContributor: Remco van 't Veer

name: Check dependency vulnerabilities

on:
  workflow_call:
  schedule:
    - cron: '30 3 * * 1'
      timezone: Europe/Amsterdam

jobs:
  nvd:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: actions/cache@v6
      with:
        key: "clojure-${{ runner.os }}-${{ hashFiles('.github/workflows/install-binaries.sh') }}"
        path: |
          ./bin
          ./lib

    - name: Install clojure and bb runtime
      run: |
        ./.github/workflows/install-binaries.sh
        echo "${PWD}/bin" >> $GITHUB_PATH

    - id: date-yymmdd
      run: 'echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_OUTPUT'

    - uses: actions/cache@v6
      with:
        path: "~/.m2"
        key: nvd-${{ steps.date-yymmdd.outputs.date }}
        restore-keys: |
          nvd-

    - name: Check clojure dependencies with NVD
      run: |
        make nvd
