# SPDX-FileCopyrightText: 2026 SURF B.V.
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0

on:
  push: { tags: [ "*" ] }

jobs:
  # No need to run job_check.yml, already run by push.yml

  build:
    uses: ./.github/workflows/job_build.yml
    secrets: inherit

  nvd:
    uses: ./.github/workflows/job_nvd.yml
